### PR TITLE
fix and refactoring

### PR DESCRIPTION
**Pull request by XpycT**
- fix issue #5
- remove Logging.(cpp|h)

### CODE REVIEW

**Review by DominikPeacock — CHANGES_REQUESTED** [review]
Hey, thanks for your effort!
Quick feedback:
- The previous file structure in Resources was quite important. The generated module should have a Public and Private folder. With these changes, they'll all be placed in the root module folder. Could you move the files back to the original structure, please?
- I'd like to keep the logging code declaration in a separate file. This is a common practice in the engine code, and I'd like to adhere to it.
- The actual changes within the file are good!

**Comment by XpycT** [comment]
fixed =)

**Review by DominikPeacock — COMMENTED** [review]
Thank you. Looks good. I will do a little QA on Saturday and will approve it then!

**Review by DominikPeacock — COMMENTED** [review]
Btw, are you looking for Unreal C++ freelance work? It's for virtual production projects for Epic.

**Pull request closed without merging**
